---
- name: Playbook for deploying Symfony API
  hosts:
    - serveur1.example.com
  become: true

  tasks:
  - name: Update packages cache
    apt:
      update_cache: yes

  - name: Install necessary packages
    apt:
      name:
        - nginx
        - php8.0-fpm
        - php8.0-cli
        - php8.0-mysql
        - php8.0-curl
        - php8.0-xml
        - php8.0-zip
        - unzip
      state: present

  - name: Configure Nginx virtual host
    template:
      src: templates/nginx-vhost.j2
      dest: /etc/nginx/sites-available/myapp
      owner: root
      group: root
      mode: "0644"

  - name: Enable Nginx virtual host
    file:
      src: /etc/nginx/sites-available/myapp
      dest: /etc/nginx/sites-enabled/myapp
      state: link
      owner: root
      group: root
      mode: "0644"

  - name: Restart Nginx
    systemd:
      name: nginx
      state: restarted

